window.debug = false;
var config = {
  urlArgs: "==version==",
  waitSeconds : 0,
  baseUrl: 'js',
  paths: {
    'toolkit' : "../../toolkit",
    'component' : "../../toolkit/component",
    'echartGalleryJs': "../../node_modules/echarts-gl/dist/echarts-gl.min",
    'ace': '../../bower_components/ace/lib/ace',
    'keyboardJS': '../../bower_components/keyboardjs/dist/keyboard',
    'moment': '../../bower_components/moment/min/moment.min',
    'jquery': '../../bower_components/jquery/dist/jquery.min',
    'angular': '../../bower_components/angular/angular.min',
    'angular-route': '../../bower_components/angular-route/angular-route.min',
    'angular-resource': '../../bower_components/angular-resource/angular-resource.min',
    'angular-animate': '../../bower_components/angular-animate/angular-animate.min',
    'angular-growl': '../../bower_components/angular-growl-v2/build/angular-growl.min',
    'ng-dialog': '../../bower_components/ng-dialog/js/ngDialog.min',
    'angular-style':'../../toolkit/angular-custom/angular-style',
    'angular-popup':'../../toolkit/angular-custom/angular-popup',
    'angular-dialogue':'../../toolkit/angular-custom/angular-dialogue',
    'jquery-ui' : "../../bower_components/jquery-ui/jquery-ui.min",
    'jquery-cookie' : "../../bower_components/jquery.cookie/jquery.cookie",
    'jquery-session' : "../../toolkit/jquery-session",
    'select2': '../../bower_components/select2/dist/js/select2.min',
    'datatables.net': '../../bower_components/datatables.net/js/jquery.dataTables.min',
    'datatables.net-bs': '../../bower_components/datatables.net-bs/js/dataTables.bootstrap.min',
    'datatables.net-buttons': '../../bower_components/datatables.net-buttons/js/dataTables.buttons',
    'datatables.net-buttons-bs': '../../bower_components/datatables.net-buttons-bs/js/buttons.bootstrap',
    'datatables.buttons.html5': '../../bower_components/datatables.net-buttons/js/buttons.html5',
    'datatables.net-select': '../../bower_components/datatables.net-select/js/dataTables.select.min',
    'bootstrap-daterangepicker': '../../bower_components/bootstrap-daterangepicker/daterangepicker',
    'underscore' : '../../bower_components/underscore/underscore',
    'domReady' : '../../bower_components/requirejs-domready/domReady',
    'zrColor' : '../../../bower_components/zrender/src/tool/color',
    'slimscroll': '../../bower_components/jquery-slimscroll/jquery.slimscroll.min',
    'macarons': '../../bower_components/echarts/theme/macarons',
    'dark': '../../bower_components/echarts/theme/dark',
    'spectrum' : '../../bower_components/spectrum/spectrum',
    'echarts': '../../bower_components/echarts/dist/echarts.min',
    'bootstrap': '../../bower_components/bootstrap/dist/js/bootstrap.min',
    'bootstrap-dialog': '../../bower_components/bootstrap3-dialog/dist/js/bootstrap-dialog.min',
    'bootstrap-multiselect': '../../bower_components/bootstrap-multiselect/dist/js/bootstrap-multiselect',
    'bmap': '../../bower_components/echarts/dist/extension/bmap.min',
    'd3' : '../../bower_components/d3/d3.min',
    'd3-transition' : '../../bower_components/d3-transition/build/d3-transition.min',
    'lodash': '../../bower_components/lodash/lodash',
    'rappid-joint': '../../toolkit/rappid/dist/rappid',
    'ckplayer' : '../../toolkit/ckplayer/ckplayer',
    'ezuikit' : '../../toolkit/ezuikit',
    'slick': '../../bower_components/slick-carousel/slick/slick.min',
    'config' : 'config',
    'directive' : 'directives/index',
    'service' : 'services/index',
    'filter' : 'filters/index',
    'value' : 'values/index',
    'index-app': '../../toolkit/admin-lte/app',
    'controller' : 'controllers/index',
    'optionDataHandler' : 'toolkit/optionDataHandler',
    'profile' : 'toolkit/profile',
    'modelPanel' : 'toolkit/modelPanel',
    'setting' : 'toolkit/setting',
    'dom' : 'toolkit/dom',
    'static' : 'toolkit/static',
    'codeMirrorEditor' : 'toolkit/codeMirror',
    'colorPicker' : 'toolkit/colorPicker',
    'grid_controller' : 'toolkit/grid_controller',
    'echart_creator' : 'toolkit/echart_creator',
    'optionEdit' : 'toolkit/optionEdit',
    'commonlib' : '../../toolkit/commonLib/js/lib/commonlib',
    'Array' : '../../toolkit/commonLib/js/lib/Array',
    'sparkline': '../../toolkit/sparkline/dist/jquery.sparkline.min',
    'tools': '../../toolkit/tools',
    'configs': '../../toolkit/configs',
    'free-board': '../../toolkit/component/free-board',
    'svgcharts': '../../toolkit/svgcharts/svgcharts',
    'app' : 'app',
    'backbone': '../../bower_components/backbone/backbone',
    'baiduMap': 'https://api.map.baidu.com/getscript?v=2.0&ak=eMekSXxqG1j2wLM57RFN61l8T6eB1EDx&services=',
    'BMapLib' : '../../toolkit/component/BMapLib',
    'echartsall' : '../../toolkit/echart-addon/echarts-all',
    'dataTools' : '../../toolkit/echart-addon/dataTool.min',
    'contextmenu' : '../../toolkit/contextmenu/contextmenu',
    'handsontable' : '../../bower_components/handsontable/dist/handsontable.full',
    'clipboard': '../../bower_components/clipboard/dist/clipboard.min',
    'zeroclipboard' : '../../bower_components/zeroclipboard/dist/ZeroClipboard.min',
    'loader' : '../../js/loader',
    'simulate' : '../../toolkit/component/simulate',
    'simulate_time' : '../../toolkit/component/simulate_time',
    'commonMethod' : '../../toolkit/component/commonMethod',
    'dropdowntree' : '../../toolkit/component/dropdowntree',
    'autocomplete' : '../../toolkit/component/autocomplete',
    'clock' : '../../toolkit/component/explainer/clock',
    'html2canvas' :'../../bower_components/html2canvas/build/html2canvas'
  },
  shim: {
    'echart_v2' : { exports: 'echarts' },
    'index-app' : { deps: ['jquery', 'jquery-ui'] },
    'slimscroll': {
      deps: ['jquery']
    },
    'html2canvas': {
      deps: ['jquery']
    },
    'bootstrap-multiselect': {
      deps: ['jquery', 'bootstrap']
    },
    'ng-dialog': {
      deps: ['angular']
    },
    'jquery' : { exports: 'jquery' },
    'jquery-ui' : { deps: ['jquery'] },
    'jquery-cookie' : { deps: ['jquery'] },
    'jquery-session' : { deps : ['jquery'] },
    'contextmenu' : { deps: ['jquery'] },
    'spectrum' : { deps: ['jquery'] },
    'angular' : { exports: 'angular' },
    'angular-route': { deps: ['angular'] },
    'angular-resource' : { deps: ['angular'] },
    'angular-animate' : { deps: ['angular'] },
    'angular-growl': { deps: ['angular'] },
    'angular-style': { deps: ['angular'] },
    'angular-popup': { deps: ['angular'] },
    'underscore' : {exports : '_'},
    'zrender' : {experts : 'zrender'},
    'angular-dialogue' : { deps: ['angular'] },
    'tools' : { deps : ['jquery']},
    'bootstrap': {
      deps: ['jquery']
    }
  },
  deps: ['angular-bootstrap', 'tools', 'html2canvas', 'Array', 'slimscroll', 'jquery-ui','index-app', 'bootstrap-multiselect', 'contextmenu', 'loader']
}
if(window.debug == true)
{
  config.paths.angular = '../../toolkit/angular-for-debug'
}
require.config(config);